### ISSUE TITLE
Encoding bug on Python side

### ISSUE THREAD

**Issue by brettviren** [brettviren/zio#1]
Haiwang found the Python and C++ sides were using different byte order for storing the message part size.  We keep C++ as is since this encoding is what's soon (hopefully) to be merged into cppzmq.

This is fixed in 17a9becbfd071499069614ee0148b1c0811dac56

```
$ ./test/check_codec.sh
```

tests all possible mix of C++ and Python for client and server.

**Comment by brettviren** [comment]
Reopen as there is some consolidation needed.  Adding domo duplicated encode/decode Python-side code which is still broken.

**Comment by HaiwangYu** [comment]
Is the python encode/decode still different from cpp?

**Comment by brettviren** [comment]
For right now, effectively "yes". And, I'm working on it.

Besides different code paths (flow vs domo) between `zio::Message` and `send()/recv()` leading to different enc/dec there are also some differences/bugs in how multipart messages are handled with the ROUTER/DEALER pair.  

Nothing really big, just some clean up and factoring to do.  Hopeully it will be cleaned up later today.

**Comment by HaiwangYu** [comment]
I see, thanks!

**Comment by brettviren** [comment]
This test:

```
$ ./test/check_codec.sh
```

now exercises all valid combo of C++/Python, ROUTER/SERVER and DEALER/CLIENT.

**Comment by HaiwangYu** [comment]
Thanks for this update. The order issue was fixed for me.
One small thing: `import sys` needed for this
https://github.com/brettviren/zio/blob/master/python/zio/util.py#L197

**Comment by brettviren** [comment]
Thanks.  The `import sys` is added in 9e1e9ef71a6d705966bff0233f327dc12a8288ee
