### ISSUE TITLE
Compile flags are too relaxed.

### ISSUE THREAD

**Issue by brettviren** [brettviren/zio#5]
When WCT builds against ZIO it finds build errors because ZIO build flags have been unintentionally left very relaxed all this time.

**Comment by HaiwangYu** [comment]
Yes, I encountered two issues compiling against WCT.
- #4 
- This [variable](https://github.com/brettviren/zio/blob/master/inc/zio/tens.hpp#L15) was causing linking error when multiple files including this header.

I made some temporary fixes locally.  Sorry forgot to mention those.

**Comment by brettviren** [comment]
No worries.

Cleaning this up required some minor API and internal changes related to how low-level recv()/send() error returns are handled (or rather, were not being handled).  Fix inbound.
